[package]
name = "peach-dyndns-host"
version = "0.1.0"
authors = ["Michael Williams <michael.williams@enspiral.com>"]
edition = "2018"

[dependencies]
futures = "0.1.26"
log = "0.4.1"
tokio = "0.1"
tokio-executor = "0.1"
tokio-tcp = "0.1"
tokio-udp = "0.1"
trust-dns = "0.16"
trust-dns-server = "0.16"
nest = "1.0.0"
hyper = "0.12"
